### ISSUE TITLE
Simple Icons Integration?

### ISSUE THREAD

**Issue by hjdhjd** [homebridge/branding#4]
Hi guys - quick question out of an abundance of caution. Are you okay with Simple Icons integration simpleicons.org - it would allow for easier integration of the logo into page badges when using services like shields.io - there's already logo support for various other automation platforms (Home Assistant, etc.).

I created an issue at Simple Icons, but before going ahead...wanted to see if someone here wants to take it up, or if you're okay with me (or someone else) taking this up.

Issue: https://github.com/simple-icons/simple-icons/issues/3464

Thanks!

**Comment by oznu** [comment]
Go for it 😄

**Comment by hjdhjd** [comment]
Didn’t think it’d be an issue, but wanted to validate. :smile:
